# Generated by Django 5.2.12 on 2026-03-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0002_dynamicrecord_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicmodel',
            name='show_in_employee_form',
            field=models.BooleanField(default=False),
        ),
    ]
