# Generated by Django 5.2.12 on 2026-03-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0004_merge_0002_dynamicfield_visible_to_users_0003_dynamicmodel_show_in_employee_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean'), ('email', 'Email'), ('file', 'File'), ('image', 'Image')], max_length=20),
        ),
    ]
