# Generated by Django 5.2.12 on 2026-03-24

import datetime
import django.db.models.deletion
from django.db import migrations, models


def _backfill_attendance_breaks(apps, schema_editor):
    DynamicRecord = apps.get_model('dynamic_models', 'DynamicRecord')
    AttendanceBreak = apps.get_model('dynamic_models', 'AttendanceBreak')

    qs = DynamicRecord.objects.select_related('dynamic_model').filter(dynamic_model__slug='attendance')
    for record in qs.iterator():
        data = record.data or {}
        sessions = data.get('break_sessions')
        if not isinstance(sessions, list):
            continue

        rows = []
        for item in sessions:
            if not isinstance(item, dict):
                continue
            break_in_raw = str(item.get('break_in') or '').strip()
            break_out_raw = str(item.get('break_out') or '').strip()
            if not break_in_raw:
                continue
            try:
                break_in = datetime.time.fromisoformat(break_in_raw)
            except ValueError:
                continue
            break_out = None
            if break_out_raw:
                try:
                    break_out = datetime.time.fromisoformat(break_out_raw)
                except ValueError:
                    break_out = None
            rows.append(AttendanceBreak(attendance_record_id=record.id, break_in=break_in, break_out=break_out))

        if rows:
            AttendanceBreak.objects.bulk_create(rows)


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0005_alter_dynamicfield_field_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_in', models.TimeField()),
                ('break_out', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='dynamic_models.dynamicrecord')),
            ],
            options={
                'ordering': ('break_in', 'id'),
            },
        ),
        migrations.RunPython(_backfill_attendance_breaks, migrations.RunPython.noop),
    ]
