# Generated by Django 5.2.12 on 2026-03-06 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_enabled_addons'),
        ('leaves', '0002_leaverequest_hr_leaverequest_hr_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('max_days_per_year', models.PositiveIntegerField(default=0)),
                ('is_paid', models.BooleanField(default=True)),
                ('color', models.CharField(blank=True, default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_types', to='clients.client')),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('client', 'name')},
            },
        ),
    ]
