# Generated by Django 5.2.12 on 2026-03-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_leavetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='leave_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_unit',
            field=models.CharField(choices=[('day', 'Day'), ('hour', 'Hour')], default='day', max_length=10),
        ),
    ]
