# Generated by Django 5.2.12 on 2026-03-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0004_leaverequest_leave_hours_leaverequest_leave_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_unit',
            field=models.CharField(
                choices=[('day', 'Day'), ('half_day', 'Half Day'), ('hour', 'Hour')],
                default='day',
                max_length=10,
            ),
        ),
    ]
