# Generated by Django 5.2.12 on 2026-03-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0005_alter_leaverequest_leave_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='half_day_slot',
            field=models.CharField(
                blank=True,
                choices=[('first_half', 'First Half'), ('second_half', 'Second Half')],
                default='',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
