# Generated by Django 5.2.12 on 2026-03-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('hr', 'HR'), ('manager', 'Manager')], default='employee', max_length=20),
        ),
    ]
