# Generated by Django 5.2.12 on 2026-03-24

from django.db import migrations, models


def _backfill_employee_code(apps, schema_editor):
    Employee = apps.get_model('employees', 'Employee')
    for row in Employee.objects.filter(employee_code__isnull=True).iterator():
        row.employee_code = f'EMP{row.id:05d}'
        row.save(update_fields=['employee_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_client_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.RunPython(_backfill_employee_code, migrations.RunPython.noop),
    ]
