# Generated by Django 5.2.12 on 2026-03-10 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0005_client_app_settings'),
        ('employees', '0004_alter_employee_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCompensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compensation', to='employees.employee')),
            ],
            options={
                'ordering': ('employee_id',),
            },
        ),
        migrations.CreateModel(
            name='PayrollPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_working_days', models.PositiveIntegerField(default=24)),
                ('standard_hours_per_day', models.DecimalField(decimal_places=2, default=8, max_digits=5)),
                ('allow_extra_hours_payout', models.BooleanField(default=False)),
                ('allow_extra_days_payout', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_policy', to='clients.client')),
            ],
            options={
                'ordering': ('client_id',),
            },
        ),
    ]
