# Generated by Django 5.2.12 on 2026-03-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollpolicy',
            name='salary_basis',
            field=models.CharField(choices=[('day', 'Day'), ('hour', 'Hour')], default='day', max_length=10),
        ),
    ]
