# Generated by Django 5.2.12 on 2026-03-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payrollpolicy_salary_basis'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecompensation',
            name='daily_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='employeecompensation',
            name='hourly_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='employeecompensation',
            name='salary_basis',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('daily', 'Daily'), ('hourly', 'Hourly')], default='monthly', max_length=10),
        ),
        migrations.AlterField(
            model_name='employeecompensation',
            name='monthly_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
