# Generated by Django 5.2.12 on 2026-03-24 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
        ('payroll', '0003_employeecompensation_daily_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecompensation',
            name='shift',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='employee_compensations',
                to='shifts.shift',
            ),
        ),
    ]
