# Generated by Django 5.2.12 on 2026-03-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='schema_name',
            field=models.SlugField(blank=True, max_length=63, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='schema_provisioned',
            field=models.BooleanField(default=False),
        ),
    ]
