# Generated by Django 5.2.12 on 2026-03-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_enabled_addons'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='app_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
