# Generated by Django 5.2.12 on 2026-03-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('view', 'View'), ('get', 'Get'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('click', 'Click'), ('other', 'Other')], default='other', max_length=16),
        ),
    ]
