"""
Django settings for hrm_project project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import re

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_dotenv():
    env_candidates = [BASE_DIR.parent / '.env', BASE_DIR / '.env']
    for env_path in env_candidates:
        if not env_path.exists():
            continue
        for raw_line in env_path.read_text(encoding='utf-8').splitlines():
            line = raw_line.strip()
            if not line or line.startswith('#') or '=' not in line:
                continue
            key, value = line.split('=', 1)
            key = key.strip()
            value = value.strip().strip('"').strip("'")
            os.environ.setdefault(key, value)


_load_dotenv()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

def _env_bool(name, default=False):
    raw = str(os.getenv(name, str(default))).strip().lower()
    return raw in ('1', 'true', 'yes', 'on')


def _env_csv(name, default=''):
    return [part.strip() for part in os.getenv(name, default).split(',') if part.strip()]


def _resolve_sqlite_db_name():
    raw = str(os.getenv('DJANGO_DB_NAME', '')).strip()
    default_db = BASE_DIR / 'HRM_db.sqlite3'
    if not raw:
        return str(default_db)

    # If Windows-style path is present on Linux host, fallback to default local DB.
    if os.name != 'nt' and re.match(r'^[A-Za-z]:[\\/]', raw):
        return str(default_db)

    db_path = Path(raw)
    if not db_path.is_absolute():
        db_path = BASE_DIR / db_path
    db_path.parent.mkdir(parents=True, exist_ok=True)
    return str(db_path)


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-change-me-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool('DJANGO_DEBUG', True)
DEMO_MODE = _env_bool('DEMO_MODE', False)

ALLOWED_HOSTS = _env_csv(
    'DJANGO_ALLOWED_HOSTS',
    '127.0.0.1,localhost,192.168.1.66',
)

CSRF_TRUSTED_ORIGINS = _env_csv(
    'DJANGO_CSRF_TRUSTED_ORIGINS',
    'http://127.0.0.1:8000,http://127.0.0.1:8001,http://localhost:8000,http://localhost:8001,http://192.168.1.66:8000,http://192.168.1.66:8001,https://jenilevenmore.pythonanywhere.com'
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'core',

    'accounts',
    'clients',
    'employees',
    'custom_fields',
    'dynamic_models',
    'attendance',
    'leaves',
    'holidays',
    'payroll',
    'policies',
    'documents',
    'shifts',
    'banks',
    'activity_logs',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # 'core.middleware.ClientExecutionKeyMiddleware',
    'core.middleware.DemoModeMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'activity_logs.middleware.ActivityLogMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.AuthRequiredMiddleware',
]

ROOT_URLCONF = 'hrm_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.jinja2.Jinja2',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': False,
        'OPTIONS': {
            'environment': 'hrm_project.jinja2.environment',
        },
    },
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hrm_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


# DATABASES = {
#         "default": {
#             "ENGINE": "django.db.backends.postgresql",
#             "NAME": os.getenv('DJANGO_PG_NAME', 'HRM'),
#             "USER": os.getenv('DJANGO_PG_USER', 'admin'),
#             "PASSWORD": os.getenv('DJANGO_PG_PASSWORD', 'admin'),
#             "HOST": os.getenv('DJANGO_PG_HOST', 'localhost'),
#             "PORT": os.getenv('DJANGO_PG_PORT', '5433'),
#         }
#     }

DB_ENGINE = os.getenv('DJANGO_DB_ENGINE', 'sqlite').strip().lower()
if DB_ENGINE in ('postgres', 'postgresql'):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv('DJANGO_PG_NAME', 'HRM'),
            "USER": os.getenv('DJANGO_PG_USER', 'admin'),
            "PASSWORD": os.getenv('DJANGO_PG_PASSWORD', 'admin'),
            "HOST": os.getenv('DJANGO_PG_HOST', 'localhost'),
            "PORT": os.getenv('DJANGO_PG_PORT', '5433'),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": _resolve_sqlite_db_name(),
        }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = str(os.getenv('DJANGO_TIME_ZONE', 'Asia/Kolkata')).strip() or 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = os.getenv('DJANGO_STATIC_URL', '/static/')
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = os.getenv('DJANGO_STATIC_ROOT', str(BASE_DIR / 'staticfiles'))
MEDIA_URL = os.getenv('DJANGO_MEDIA_URL', '/media/')
MEDIA_ROOT = os.getenv('DJANGO_MEDIA_ROOT', str(BASE_DIR / 'media'))

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

from datetime import timedelta

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# Multi-schema tenant provisioning (PostgreSQL only).
# Set True after switching DATABASES['default'] to PostgreSQL.
CLIENT_SCHEMA_AUTO_PROVISION = True
CLIENT_SCHEMA_MIGRATE_DATABASE = 'default'


EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = _env_bool('EMAIL_USE_TLS', True)
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'no-reply@example.com')

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
SESSION_COOKIE_SECURE = _env_bool('SESSION_COOKIE_SECURE', not DEBUG)
CSRF_COOKIE_SECURE = _env_bool('CSRF_COOKIE_SECURE', not DEBUG)
SECURE_SSL_REDIRECT = _env_bool('SECURE_SSL_REDIRECT', False)
APP_URL_PREFIX = '/' + str(os.getenv('APP_URL_PREFIX', 'hrm')).strip().strip('/')
if APP_URL_PREFIX == '/':
    APP_URL_PREFIX = ''
BACKEND_API_URL = os.getenv('BACKEND_API_URL', 'http://127.0.0.1:8000')
USE_INTERNAL_API = _env_bool('USE_INTERNAL_API', True)
CLIENT_EXECUTION_SECRET_KEY = str(os.getenv('CLIENT_EXECUTION_SECRET_KEY', '')).strip()

FRONTEND_BASE_URLS = [
    url.strip().rstrip('/')
    for url in os.getenv(
        'FRONTEND_BASE_URLS',
        'http://127.0.0.1:8000,http://192.168.1.66:8000'
    ).split(',')
    if url.strip()
]
FRONTEND_BASE_URL = os.getenv(
    'FRONTEND_BASE_URL',
    FRONTEND_BASE_URLS[0] if FRONTEND_BASE_URLS else 'http://127.0.0.1:8000',
).rstrip('/')

