# Generated by Django 5.2.12 on 2026-03-25 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0007_clientrole_enabled_addons_clientrole_module_permissions'),
        ('employees', '0006_employee_employee_code'),
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('leave', 'Leave'), ('half-day', 'Half Day')], default='present', max_length=20)),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='clients.client')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employee')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='shifts.shift')),
            ],
            options={
                'ordering': ('-attendance_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='AttendanceBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_in', models.TimeField()),
                ('break_out', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='attendance.attendancerecord')),
            ],
            options={
                'ordering': ('break_in', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['client', 'attendance_date'], name='attendance__client__19267b_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['employee', 'attendance_date'], name='attendance__employe_a000ce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('employee', 'attendance_date')},
        ),
        migrations.AddIndex(
            model_name='attendancebreak',
            index=models.Index(fields=['attendance'], name='attendance__attenda_2d6ffe_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancebreak',
            index=models.Index(fields=['attendance', 'break_out'], name='attendance__attenda_cb6df7_idx'),
        ),
    ]
