# Generated by Django 5.2.12 on 2026-03-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_clientpermissiongroup_userprofile_permission_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpermissiongroup',
            name='enabled_addons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='enabled_addons',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
